### ISSUE TITLE
error with last version of docrep 

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#133]
**Describe the bug**
Scpy does not loads after fresh install from scratch

**To Reproduce**
1. install spectrochempy as indicated 
2. run: "from spectrochempy import *"
3. the following error occurs at 8%: ImportError: spectrochempy.core.dataset.ndarray

**Pycharm  debugger output:**
Connected to pydev debugger (build 201.8743.11)
Loading SpectroChemPy API:   8%|▊         | 92/1211 [00:00<00:59, 18.79it/s]Traceback (most recent call last):
  File "C:\Miniconda3\envs\scpy-r\lib\site-packages\spectrochempy\utils\file.py", line 347, in generate_api
    pkg = import_item(pkg)
  File "C:\Miniconda3\envs\scpy-r\lib\site-packages\traitlets\utils\importstring.py", line 34, in import_item
    module = __import__(package, fromlist=[obj])
  File "C:\Miniconda3\envs\scpy-r\lib\site-packages\spectrochempy\core\dataset\ndarray.py", line 68, in <module>
    class NDArray(HasTraits):
  File "C:\Miniconda3\envs\scpy-r\lib\site-packages\spectrochempy\core\dataset\ndarray.py", line 115, in NDArray
    @docstrings.get_sectionsf('NDArray')
  File "C:\Miniconda3\envs\scpy-r\lib\site-packages\docrep\decorators.py", line 110, in deprecated
    return func(self, *args, **kwargs)
  File "C:\Miniconda3\envs\scpy-r\lib\site-packages\docrep\__init__.py", line 927, in get_sectionsf
    return self.get_sections(base=args[0], *args[1:], **kwargs)
TypeError: get_sections() missing 1 required positional argument: 's'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Miniconda3\envs\scpy-r\lib\site-packages\spectrochempy\__init__.py", line 63, in <module>
    from spectrochempy.api import *    # noqa: F403,F401
  File "C:\Miniconda3\envs\scpy-r\lib\site-packages\spectrochempy\api.py", line 123, in <module>
    from spectrochempy.core import *         # noqa: F403, F401, E402
  File "C:\Miniconda3\envs\scpy-r\lib\site-packages\spectrochempy\core\__init__.py", line 239, in <module>
    from spectrochempy.core.dataset.api import *     # noqa: E402,F403,F401
  File "C:\Miniconda3\envs\scpy-r\lib\site-packages\spectrochempy\core\dataset\api.py", line 12, in <module>
    __all__ = generate_api(__file__)
  File "C:\Miniconda3\envs\scpy-r\lib\site-packages\spectrochempy\utils\file.py", line 349, in generate_api
    raise ImportError(pkg)
ImportError: spectrochempy.core.dataset.ndarray
Loading SpectroChemPy API:   8%|▊         | 92/1211 [00:17<03:34,  5.23it/s]

**Provisional fix**
the error is due to an upgrade of the repdoc package. Scpy works fine with docrep 0.2.7 (May 24, 2019) but not with next versions,  0.3.0. (Aug 26, 2020) or 0.3.1. (sept 12, 2020).

=> reinstall previous docrep version (conda install docrep=0.2.7) after fresh install or fix docrep version in requirements or fix scpy code to work with docrep 0.3+

**Comment by atravert** [comment]
To fix scpy with respect to docrep, see:  https://docrep.readthedocs.io/en/latest/#migrate-to-0-3

**Comment by atravert** [comment]
The provisional FIX consists in pinning a previous version of docrep. IOt should be made more permamanent by either updating the scpy code using docrep or not using docrep anymore for the documentation.

**Comment by fernandezc** [comment]
I made modification of the code so last version of docrep is now working.  Will be soon available in the next release. Other fixes with traitlets needed before doing the pull request.
