### ISSUE TITLE
[Bug]: scp.read() with conda/mamba install, > 0.4.2 

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#468]
### What happened?

@Aboulaytreda has reported that read() is not recognised (module 'spectrochempy' has no attribute 'read') after upgrading from 0.4.2 to 0.4.5  or dev (0.4.6) version.

After few checks on my side it appears that:
- developper install (though git clone) works fine
- pip install works fine for 0.4.2 and 0.4.5
- conda/mamba install is only OK for scpy == 0.4.2, not for 0.4.4 or 0.4.5  [there is no conda release for 0.4.3]

other modules or functions are found, e.g; scp.NDDataset() , scp.set_loglevel() ); I didn't check extensively for the others 

### What did you expect to happen?

read() should work after conda install

### Environment

Note that  scp.show_versions() does not work fine
## scpy 0.3.5 installed with conda:
![image](https://user-images.githubusercontent.com/10098314/168095424-fd9777d4-9f1a-447e-a859-70aeb763de5f.png)

## scpy 0.3.5 installed with pip (after conda remove / pip install):
![image](https://user-images.githubusercontent.com/10098314/168097475-d62d43f9-c383-4ed8-8110-368f94c3d12d.png)

**Comment by fernandezc** [comment]
Hi, I'll try to watch it this weekend.

**Comment by atravert** [comment]
Merci !

**Comment by fernandezc** [comment]
Last dev  version (dev11) should be OK. The problem was , I think related to some missing dependencies  in the meta.yaml conda recipe. 
I have removed non-working version from CONDA, and I prepared a release 0.4.6 (to be published if you confirm that the conda dev work for you) 

reminder: use `mamba or conda  install -c spectrocat/label/dev spectrochempy` to install it.

**Comment by fernandezc** [comment]
## Environment
> Note that scp.show_versions() does not work fine

Yes, after checking I see that this work only for developers  when environment.yml is accessible. In user version, this file is not present in `site-package` and thus this cannot work. 
Probably the best is to replace this by `conda list --export` (when working in conda environmen or `pip freeze` for pip. 
I will indicate this in the issues template!
